# Generated by Django 4.1.5 on 2023-01-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_color_alter_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
