# Generated by Django 4.1.5 on 2023-01-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
